name: Assign PR to creator

on: [pull_request]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to creator
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      uses: thomaseizinger/assign-pr-creator-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
