name: Assign PR to creator

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR author
      uses: thomaseizinger/assign-pr-creator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
