name: Assign PR to creator

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR author
      uses: thomaseizinger/assign-pr-creator-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
